#!/usr/bin/env node
/**
 * Turns a niche config into the two things the running system needs:
 *
 *   1. db/seed.generated.sql  — the sources rows to load into Supabase
 *   2. .env.generated         — the NICHE_* variables for the n8n container
 *
 *   node scripts/apply-niche.mjs ai-governance
 *
 * Nothing here talks to a live service. Review both outputs, then apply the SQL
 * in the Supabase SQL editor and merge the env vars into your .env.
 */

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const nicheDir = join(root, "config", "niches");

const slug = process.argv[2];
const available = readdirSync(nicheDir)
  .filter((f) => f.endsWith(".yml"))
  .map((f) => f.replace(/\.yml$/, ""));

if (!slug || !available.includes(slug)) {
  console.error(
    `Usage: node scripts/apply-niche.mjs <slug>\n\nAvailable: ${available.join(", ")}`
  );
  process.exit(1);
}

const cfg = parse(readFileSync(join(nicheDir, `${slug}.yml`), "utf8"));

/* --------------------------------------------------------------- validate */

const problems = [];
const need = (path, value) => {
  if (value === undefined || value === null || value === "") {
    problems.push(`missing: ${path}`);
  }
};

need("slug", cfg.slug);
need("name", cfg.name);
need("audience", cfg.audience);
need("digest.cron", cfg.digest?.cron);
need("pricing.monthly_usd", cfg.pricing?.monthly_usd);

if (cfg.slug !== slug) {
  problems.push(`slug mismatch: file is "${slug}.yml" but slug field is "${cfg.slug}"`);
}
if (!Array.isArray(cfg.sources) || cfg.sources.length === 0) {
  problems.push("sources: at least one source is required");
}

for (const [i, s] of (cfg.sources ?? []).entries()) {
  if (!s.url || !/^https?:\/\//.test(s.url)) {
    problems.push(`sources[${i}].url: must be an absolute http(s) URL`);
  }
  if (!s.name) problems.push(`sources[${i}].name: required`);
  if (s.kind && !["rss", "atom", "json"].includes(s.kind)) {
    problems.push(`sources[${i}].kind: must be rss, atom, or json`);
  }
}

// Cheap sanity check on the cron: 5 space-separated fields.
if (cfg.digest?.cron && cfg.digest.cron.trim().split(/\s+/).length !== 5) {
  problems.push(`digest.cron: expected 5 fields, got "${cfg.digest.cron}"`);
}

if (problems.length) {
  console.error(`\n${slug}.yml has ${problems.length} problem(s):\n`);
  for (const p of problems) console.error(`  - ${p}`);
  console.error("");
  process.exit(1);
}

/* ------------------------------------------------------------------ emit */

const sq = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`;

const values = cfg.sources
  .map(
    (s) =>
      `  (${sq(cfg.slug)}, ${sq(s.name)}, ${sq(s.url)}, ${sq(s.kind ?? "rss")}, ${sq(
        (s.context ?? "").trim()
      )})`
  )
  .join(",\n");

const sql = `-- Generated by scripts/apply-niche.mjs from config/niches/${slug}.yml
-- Safe to re-run: conflicting rows are updated, not duplicated.
-- Run db/schema.sql first.

insert into sources (niche, name, url, kind, context) values
${values}
on conflict (niche, url) do update
  set name = excluded.name,
      kind = excluded.kind,
      context = excluded.context,
      active = true;
`;

writeFileSync(join(root, "db", "seed.generated.sql"), sql);

const oneLine = (s) => String(s ?? "").replace(/\s+/g, " ").trim();
const pipe = (list) => (list ?? []).map(oneLine).join("|");

const env = `# Generated by scripts/apply-niche.mjs from config/niches/${slug}.yml
# Merge these into your .env — they are the niche-specific half of the config.
# Regenerate after editing the YAML; do not hand-edit this file.

NICHE_SLUG=${cfg.slug}
NICHE_NAME=${oneLine(cfg.name)}
NICHE_TZ=${cfg.timezone ?? "UTC"}
NICHE_AUDIENCE=${oneLine(cfg.audience)}
NICHE_INCLUDE=${pipe(cfg.relevance?.include)}
NICHE_EXCLUDE=${pipe(cfg.relevance?.exclude)}
NICHE_SUBJECT=${oneLine(cfg.digest?.subject ?? `${cfg.name} — {{date}}`)}
NICHE_INTRO=${oneLine(cfg.digest?.intro ?? "")}
MAX_ITEMS=${cfg.digest?.max_items ?? 10}
MIN_SCORE=${cfg.digest?.min_score ?? 55}
`;

writeFileSync(join(root, ".env.generated"), env);

console.log(`
${cfg.name}  (${cfg.slug})

  sources        ${cfg.sources.length}
  schedule       ${cfg.digest.cron}  [${cfg.timezone ?? "UTC"}]
  price          $${cfg.pricing.monthly_usd}/mo
  cut            top ${cfg.digest?.max_items ?? 10} items scoring >= ${cfg.digest?.min_score ?? 55}

wrote db/seed.generated.sql
wrote .env.generated

Next:
  1. Run db/schema.sql then db/seed.generated.sql in the Supabase SQL editor.
  2. Merge .env.generated into .env.
  3. Set the cron on the "Weekly Trigger" node to: ${cfg.digest.cron}
`);
