-- Generated by scripts/apply-niche.mjs from config/niches/marketplace-ops.yml
-- Safe to re-run: conflicting rows are updated, not duplicated.
-- Run db/schema.sql first.

insert into sources (niche, name, url, kind, context) values
  ('marketplace-ops', 'Marketplace Pulse', 'https://www.marketplacepulse.com/rss', 'rss', 'Marketplace industry analysis — Amazon, eBay, Etsy, Shopify ecosystem.'),
  ('marketplace-ops', 'European Commission — Digital strategy news', 'https://digital-strategy.ec.europa.eu/en/rss.xml', 'rss', 'DSA/DMA enforcement and platform regulation in the EU.'),
  ('marketplace-ops', 'US FTC — Press releases', 'https://www.ftc.gov/feeds/press-release.xml', 'rss', 'Consumer protection enforcement against platforms and sellers.'),
  ('marketplace-ops', 'TechCrunch — Commerce', 'https://techcrunch.com/category/commerce/feed/', 'rss', 'Funding, launches, and shutdowns across commerce and marketplaces.')
on conflict (niche, url) do update
  set name = excluded.name,
      kind = excluded.kind,
      context = excluded.context,
      active = true;
